name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate GitHub stats
      uses: anuraghazra/github-readme-stats@v0.2.1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        username: 'Pravinkumar-Raja'
        output: 'stats.svg'  # this will generate the image

    - name: Commit & Push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add stats.svg
        git commit -m "Update GitHub Stats"
        git push
