name: Auto Update GitHub Stats

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate stats svg
        uses: anuraghazra/github-readme-stats@v0.2.1
        with:
          username: Pravinkumar-Raja
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: stats.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update stats.svg" || echo "No changes"
          git push
